import math

HOST = 'localhost'
PORT = 5000

NUM_BOTS = 1
NUM_EPISDOES = 1000


EPISODE_NUM_STEPS_MIN = 20
EPISODE_NUM_STEPS_MAX = 20
EPISODE_STEPS = 50

BOUNDSX = (2676, 2776)
BOUNDSY = (3428, 3528)

X_SIZE = BOUNDSX[1] - BOUNDSX[0]
Y_SIZE = (BOUNDSY[1] - BOUNDSY[0])



NODES_RANGE = 2
STATE_SIZE = (NODES_RANGE*2 + 1)** 2 #x,y,free space, nearby nodes
GRID_SIDE_LENGTH = int(math.sqrt(STATE_SIZE))

ACTION_SIZE = 4 #move in each direction, interact in each direction

SPAWN_LOCATION = (2727, 3478)

RELATIVE_SPAWN_LOCATION = (SPAWN_LOCATION[0] - BOUNDSX[0], SPAWN_LOCATION[1] - BOUNDSY[0])

#GOAL_LOC = (2737, 3478)
GOAL_LOC = None
#RELATIVE_GOAL_LOC = (GOAL_LOC[0] - BOUNDSX[0], GOAL_LOC[1] - BOUNDSY[0])

MODEL_SAVE_PATH = "./models/model.pt"

